### ISSUE TITLE
current @latest build's tag broken on Windows - latest points to 15.1.

### ISSUE THREAD

**Issue by rsegeda** [launchql/libpg-query-node#70]
The purpose of this issue is to save some time for future readers.

The default @latest build tag points to the 15.1.0 version installed through npm, which is broken for Windows because it uses (libpg-query@15.2.0). 

I tried to install the package on Windows:

 `pnpm add -D libpg-query`
 
 But I experienced the following error:

``` <my_project>\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\queryparser.vcxproj (default target) (4) ->
   │ (CustomBuild target) -> 
      NMAKE : fatal error U1052: file 'Makefile.msvc' not found [<my_project>\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\queryparser.vcxproj]
      NMAKE : fatal error U1052: file 'Makefile.msvc' not found [<my_project>\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\queryparser.vcxproj]
      CUSTOMBUILD : error : 'nmake' command failed [<my_project>\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query\build\queryparser.vcxproj]
      <...>\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for '..\binding.gyp' exited with code -1. [...… 
      0 Warning(s)
      4 Error(s)
```
 
It works when I install the exact version `libpg-query@16.2.0`. 

**Solution:**

 `pnpm add -D libpg-query@16.2.0`

The reason is that `15.1.0` of libpg-query-node (so as the current `@latest`) points to a broken [libpg_query](https://github.com/pganalyze/libpg_query) that has a missing 'Makefile.msvc'  file. The issue in libpg_query was fixed in [16.2.0](https://github.com/pganalyze/libpg_query/commit/f97c253c90287f5a43bc365f8c096b8a910b3bf3).

**Comment by karlhorky** [comment]
cc @pyramation we have also been experiencing this with some students, seems like Windows builds are broken

Maybe it would be good to add a minimal smoke test for installability on Windows/macOS/Linux? (eg. with a GitHub Actions workflow), and then schedule as such:

1. Run always for every PR / push
2. Since this particular issue appears to be related to the npm `latest` tag, it could also be set up with a cron schedule to run every day or every week

**Comment by Draikth** [comment]
Good day, 
I seem to be having a similar issue when I try to install an eslint update after starting a postgres database, 
Apologies if my terminolgy is wrong, I'm still new to this as I have recently started a web development course, the issue referenced above  (https://github.com/upleveled/system-setup/issues/75) by KarlHorky is mine. 

here is my l$ pnpm add --save-dev eslint-config-upleveled@latest
pnpm upleveled-eslint-install
 WARN  2 deprecated subdependencies found: @humanwhocodes/config-array@0.13.0, @humanwhocodes/object-schema@2.0.3
Already up to date
Progress: resolved 530, reused 503, downloaded 0, added 0, done
 WARN  Issues with peer dependencies found
.
├─┬ eslint-plugin-import 2.29.1
│ └── ✕ unmet peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8": found 9.3.0
└─┬ eslint-config-upleveled 8.2.1
  ├── ✕ unmet peer eslint@^9.4.0: found 9.3.0
  ├── ✕ unmet peer @types/node@>=20.14.2: found 20.12.13
  ├── ✕ unmet peer globals@^15.4.0: found 14.0.0
  ├─┬ eslint-plugin-import-x 0.5.1
  │ └─┬ @typescript-eslint/utils 7.11.0
  │   └── ✕ unmet peer eslint@^8.56.0: found 9.3.0
  ├─┬ eslint-plugin-jsx-a11y 6.8.0
  │ └── ✕ unmet peer eslint@"^3 || ^4 || ^5 || ^6 || ^7 || ^8": found 9.3.0
  ├─┬ eslint-plugin-react 7.34.2
  │ └── ✕ unmet peer eslint@"^3 || ^4 || ^5 || ^6 || ^7 || ^8": found 9.3.0
  ├─┬ eslint-plugin-testing-library 6.2.2
  │ ├── ✕ unmet peer eslint@"^7.5.0 || ^8.0.0": found 9.3.0
  │ └─┬ @typescript-eslint/utils 5.62.0
  │   └── ✕ unmet peer eslint@"^6.0.0 || ^7.0.0 || ^8.0.0": found 9.3.0
  └─┬ eslint-plugin-react-hooks 4.6.2
    └── ✕ unmet peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0": found 9.3.0

Done in 9.9s
Detected project type: Next.js with PostgreSQL
Installing 4 ESLint config dependencies...
 WARN  8 deprecated subdependencies found: @humanwhocodes/config-array@0.13.0, @humanwhocodes/object-schema@2.0.3, are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, inflight@1.0.6, npmlog@5.0.1, rimraf@3.0.2
Packages: +117
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 669, reused 619, downloaded 1, added 1, done
node_modules/.pnpm/libpg-query@15.2.0_encoding@0.1.13/node_modules/libpg-query: Running install scripnode_modules/.pnpm/libpg-query@15.2.0_encoding@0.1.13/node_modules/libpg-query: Running install script, failed in 11.9s
.../node_modules/libpg-query install$ node-pre-gyp install --fallback-to-build --loglevel verbose    
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp verb cli [
│ node-pre-gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
│ node-pre-gyp verb cli   'C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\@ma…  
│ node-pre-gyp verb cli   'install',
│ node-pre-gyp verb cli   '--fallback-to-build',
│ node-pre-gyp verb cli   '--loglevel',
│ node-pre-gyp verb cli   'verbose'
│ node-pre-gyp verb cli ]
│ node-pre-gyp info using node-pre-gyp@1.0.11
│ node-pre-gyp info using node@20.12.1 | win32 | x64
│ node-pre-gyp verb command install []
│ node-pre-gyp info check checked for "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnp…  
│ node-pre-gyp http GET https://supabase-public-artifacts-bucket.s3.amazonaws.com/libpg-query-node…  
│ node-pre-gyp ERR! install response status 404 Not Found on https://supabase-public-artifacts-buc…  
│ node-pre-gyp WARN Pre-built binaries not installable for libpg-query@15.2.0 and node@20.12.1 (no…  
│ node-pre-gyp WARN Hit error response status 404 Not Found on https://supabase-public-artifacts-b…  
│ node-pre-gyp verb command build [ 'rebuild' ]
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@10.1.0
│ gyp info using node@20.12.1 | win32 | x64
│ gyp info ok
│ gyp info it worked if it ends with ok
│ gyp verb cli [
│ gyp verb cli 'C:\\Program Files\\nodejs\\node.exe',
│ gyp verb cli 'C:\\Users\\User\\AppData\\Local\\node\\corepack\\v1\\pnpm\\9.3.0\\dist\\node_modul…  
│ gyp verb cli 'configure',
│ gyp verb cli '--fallback-to-build',
│ gyp verb cli '--loglevel=verbose',
│ gyp verb cli '--module=C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\libpg…  
│ gyp verb cli '--module_name=queryparser',
│ gyp verb cli '--module_path=C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\…  
│ gyp verb cli '--napi_version=9',
│ gyp verb cli '--node_abi_napi=napi',
│ gyp verb cli '--napi_build_version=0',
│ gyp verb cli '--node_napi_label=node-v115'
│ gyp verb cli ]
│ gyp info using node-gyp@10.1.0
│ gyp info using node@20.12.1 | win32 | x64
│ gyp verb find Python Python is not set from command line or npm configuration
│ gyp verb find Python Python is not set from environment variable PYTHON
│ gyp verb find Python checking if the py launcher can be used to find Python 3
│ gyp verb find Python - executing "py.exe" to get Python 3 executable path
│ gyp verb find Python - executable path is "C:\Python312\python.exe"
│ gyp verb find Python - executing "C:\Python312\python.exe" to get version
│ gyp verb find Python - version is "3.12.4"
│ gyp info find Python using Python version 3.12.4 found at "C:\Python312\python.exe"
│ gyp verb get node dir no --target version specified, falling back to host node version: 20.12.1    
│ gyp verb install input version string "20.12.1"
│ gyp verb install installing version: 20.12.1
│ gyp verb install --ensure was passed, so won't reinstall if already installed
│ gyp verb install version is already installed, need to check "installVersion"
│ gyp verb got "installVersion" 11
│ gyp verb needs "installVersion" 11
│ gyp verb install version is good
│ gyp verb on Windows; need to check node.lib
│ gyp verb get node dir target node version installed: 20.12.1
│ gyp verb build dir attempting to create "build" dir: C:\Users\User\projects\nextjs-ecomm-store\n…  
│ gyp verb build dir "build" dir needed to be created? Yes
│ gyp verb find VS msvs_version not set from command line or npm config
│ gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
│ gyp verb find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running wi…  
│ gyp verb find VS
│ gyp verb find VS Failure details: undefined
│ gyp verb find VS checking VS2022 (17.9.34723.18) found at:
│ gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
│ gyp verb find VS - found "Visual Studio C++ core features"
│ gyp verb find VS - found VC++ toolset: v143
│ gyp verb find VS - found Windows SDK: 10.0.22621.0
│ gyp info find VS using VS2022 (17.9.34723.18) found at:
│ gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
│ gyp info find VS run with --verbose for detailed information
│ gyp verb build/config.gypi creating config file
│ gyp verb build/config.gypi writing out config file: C:\Users\User\projects\nextjs-ecomm-store\no…  
│ gyp verb config.gypi checking for gypi file: C:\Users\User\projects\nextjs-ecomm-store\node_modu…  
│ gyp verb common.gypi checking for gypi file: C:\Users\User\projects\nextjs-ecomm-store\node_modu…  
│ gyp verb gyp gyp format was not specified; forcing "msvs"
│ gyp info spawn C:\Python312\python.exe
│ gyp info spawn args [
│ gyp info spawn args 'C:\\Users\\User\\AppData\\Local\\node\\corepack\\v1\\pnpm\\9.3.0\\dist\\nod…  
│ gyp info spawn args 'binding.gyp',
│ gyp info spawn args '-f',
│ gyp info spawn args 'msvs',
│ gyp info spawn args '-I',
│ gyp info spawn args 'C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\libpg-q…  
│ gyp info spawn args '-I',
│ gyp info spawn args 'C:\\Users\\User\\AppData\\Local\\node\\corepack\\v1\\pnpm\\9.3.0\\dist\\nod…  
│ gyp info spawn args '-I',
│ gyp info spawn args 'C:\\Users\\User\\AppData\\Local\\node-gyp\\Cache\\20.12.1\\include\\node\\c…  
│ gyp info spawn args '-Dlibrary=shared_library',
│ gyp info spawn args '-Dvisibility=default',
│ gyp info spawn args '-Dnode_root_dir=C:\\Users\\User\\AppData\\Local\\node-gyp\\Cache\\20.12.1',   
│ gyp info spawn args '-Dnode_gyp_dir=C:\\Users\\User\\AppData\\Local\\node\\corepack\\v1\\pnpm\\9…  
│ gyp info spawn args '-Dnode_lib_file=C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\node-gyp\\\\Cach…  
│ gyp info spawn args '-Dmodule_root_dir=C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modul…  
│ gyp info spawn args '-Dnode_engine=v8',
│ gyp info spawn args '--depth=.',
│ gyp info spawn args '--no-parallel',
│ gyp info spawn args '--generator-output',
│ gyp info spawn args 'C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\libpg-q…  
│ gyp info spawn args '-Goutput_dir=.'
│ gyp info spawn args ]
│ gyp info ok
│ gyp info it worked if it ends with ok
│ gyp verb cli [
│ gyp verb cli 'C:\\Program Files\\nodejs\\node.exe',
│ gyp verb cli 'C:\\Users\\User\\AppData\\Local\\node\\corepack\\v1\\pnpm\\9.3.0\\dist\\node_modul…  
│ gyp verb cli 'build',
│ gyp verb cli '--fallback-to-build',
│ gyp verb cli '--loglevel=verbose',
│ gyp verb cli '--module=C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\libpg…  
│ gyp verb cli '--module_name=queryparser',
│ gyp verb cli '--module_path=C:\\Users\\User\\projects\\nextjs-ecomm-store\\node_modules\\.pnpm\\…  
│ gyp verb cli '--napi_version=9',
│ gyp verb cli '--node_abi_napi=napi',
│ gyp verb cli '--napi_build_version=0',
│ gyp verb cli '--node_napi_label=node-v115'
│ gyp verb cli ]
│ gyp info using node-gyp@10.1.0
│ gyp info using node@20.12.1 | win32 | x64
│ gyp verb build type Release
│ gyp verb architecture x64
│ gyp verb node dev dir C:\Users\User\AppData\Local\node-gyp\Cache\20.12.1
│ gyp verb python C:\Python312\python.exe
│ gyp verb found first Solution file build\binding.sln
│ gyp verb using MSBuild: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\C…  
│ gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bi…  
│ gyp info spawn args [
│ gyp info spawn args 'build\\binding.sln',
│ gyp info spawn args '/nologo',
│ gyp info spawn args '/p:Configuration=Release;Platform=x64'
│ gyp info spawn args ]
│ Build started 13/06/2024 09:26:34.
│ Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encodin…  
│ ValidateSolutionConfiguration:
│   Building solution configuration "Release|x64".
│ Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encodin…  
│ PrepareForBuild:
│   Structured output is enabled. The formatting of compiler diagnostics will reflect the error hi…  
│   Creating directory "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@1…  
│ InitializeBuildStatus:
│   Creating "Release\obj\nothing\nothing.tlog\unsuccessfulbuild" because "AlwaysCreate" was speci…  
│   Touching "Release\obj\nothing\nothing.tlog\unsuccessfulbuild".
│ ClCompile:
│   All outputs are up-to-date.
│   All outputs are up-to-date.
│ Lib:
│   C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\H…  
│   "Release\obj\nothing\\node-addon-api@7.1.0\node_modules\node-addon-api\nothing.obj"
│   nothing.vcxproj -> C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15…  
│ FinalizeBuildStatus:
│   Deleting file "Release\obj\nothing\nothing.tlog\unsuccessfulbuild".
│   Touching "Release\obj\nothing\nothing.tlog\nothing.lastbuildstate".
│ Done Building Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@…  
│ Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encodin…  
│ Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encodin…  
│ PrepareForBuild:
│   Creating directory "Release\obj\queryparser\".
│   Structured output is enabled. The formatting of compiler diagnostics will reflect the error hi…  
│   Creating directory "Release\obj\queryparser\queryparser.tlog\".
│ InitializeBuildStatus:
│   Creating "Release\obj\queryparser\queryparser.tlog\unsuccessfulbuild" because "AlwaysCreate" w…  
│   Touching "Release\obj\queryparser\queryparser.tlog\unsuccessfulbuild".
│ CustomBuild:
│   prebuild_dependencies
│   Cloning into 'libpg_query'...
│   Note: switching to 'db39825bc7c1ddd45962ec6a626d740b7f8f027a'.
│
│   You are in 'detached HEAD' state. You can look around, make experimental
│   changes and commit them, and you can discard any commits you make in this
│   state without impacting any branches by switching back to a branch.
│
│   If you want to create a new branch to retain commits you create, you may
│   do so (now or later) by using -c with the switch command. Example:
│
│     git switch -c <new-branch-name>
│
│   Or undo this operation with:
│
│     git switch -
│
│   Turn off this advice by setting config variable advice.detachedHead to false
│
│   HEAD is now at db39825 Update changelog, prepare `15-4.2.4` release (#227)
│   "please ensure you are running at Windows Developer Command Prompt environments"
│
│   Microsoft (R) Program Maintenance Utility Version 14.39.33523.0
│   Copyright (C) Microsoft Corporation.  All rights reserved.
│
│ NMAKE : fatal error U1052: file 'Makefile.msvc' not found [C:\Users\User\projects\nextjs-ecomm-s…  
│   Stop.
│
│   Microsoft (R) Program Maintenance Utility Version 14.39.33523.0
│   Copyright (C) Microsoft Corporation.  All rights reserved.
│
│ NMAKE : fatal error U1052: file 'Makefile.msvc' not found [C:\Users\User\projects\nextjs-ecomm-s…  
│   Stop.
│ CUSTOMBUILD : error : 'nmake' command failed [C:\Users\User\projects\nextjs-ecomm-store\node_mod…  
│   File Not Found
│   "ERROR: pg_query.lib not found"
│   The system cannot find the file specified.
│           1 file(s) copied.
│ C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microso…  
│ Done Building Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@…  
│ Done Building Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@…  
│ Done Building Project "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@…  
│ Build FAILED.
│ "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13…  
│ "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13…  
│ "C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13…  
│ (CustomBuild target) ->
│   NMAKE : fatal error U1052: file 'Makefile.msvc' not found [C:\Users\User\projects\nextjs-ecomm…  
│   NMAKE : fatal error U1052: file 'Makefile.msvc' not found [C:\Users\User\projects\nextjs-ecomm…  
│   CUSTOMBUILD : error : 'nmake' command failed [C:\Users\User\projects\nextjs-ecomm-store\node_m…  
│   C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Micro…  
│     0 Warning(s)
│     4 Error(s)
│ Time Elapsed 00:00:07.18
│ gyp ERR! build error
│ gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Cu…
│ gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\User\AppData\Local\node\corepack\v1\pnpm\9.…  
│ gyp ERR! stack at ChildProcess.emit (node:events:518:28)
│ gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
│ gyp ERR! System Windows_NT 10.0.22631
│ gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Local\\node\\c…  
│ gyp ERR! cwd C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_enc…  
│ gyp ERR! node -v v20.12.1
│ gyp ERR! node-gyp -v v10.1.0
│ gyp ERR! not ok
│ node-pre-gyp ERR! build error
│ node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\User…  
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\User\projects\nextjs-ecomm-sto…  
│ node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
│ node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
│ node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)     
│ node-pre-gyp ERR! System Windows_NT 10.0.22631
│ node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\projects\\next…  
│ node-pre-gyp ERR! cwd C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@1…  
│ node-pre-gyp ERR! node -v v20.12.1
│ node-pre-gyp ERR! node-pre-gyp -v v1.0.11
│ node-pre-gyp ERR! not ok
│ Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\User\AppData\Local\node\corepack\v1…  
└─ Failed in 11.9s at C:\Users\User\projects\nextjs-ecomm-store\node_modules\.pnpm\libpg-query@15.2.0_encoding@0.1.13\node_modules\libpg-query
 ELIFECYCLE  Command failed with exit code 1.
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: pnpm add --save-dev @ts-safeql/eslint-plugin libpg-query prettier-plugin-embed prettier-plugin-sql
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at file:///C:/Users/User/projects/nextjs-ecomm-store/node_modules/.pnpm/eslint-config-upleveled@8.2.1_@babel+core@7.24.6_@types+eslint@8.56.10_@types+node@20.12.13_@_rhlrwx2pmjlwgy5t5zzhx6eroq/node_modules/eslint-config-upleveled/bin/install.js:138:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 13568,
  stdout: null,
  stderr: null
}

Node.js v20.12.1atest error block after attempting to install the eslint update 
```

```

**Comment by karlhorky** [comment]
@pyramation since it seems like it may still be a while before this is resolved, should the npm `latest` tag of `libpg-query` be set to `libpg-query@16.2.0`?

Currently it's still set to `libpg-query@ 15.2.0-rc.deparse.3`, which is broken on Windows:

![Screenshot 2024-09-08 at 17 06 43](https://github.com/user-attachments/assets/4d6e656f-5627-4738-8f94-b63f872022ec)

**Comment by pyramation** [comment]
I can do that, 15 is technically more maintained, but will do this for now :)

**Comment by karlhorky** [comment]
Great, thanks! Confirmed that [`libpg-query@16.2.0` is `latest` tag now](https://www.npmjs.com/package/libpg-query?activeTab=versions):

![Screenshot 2024-09-25 at 10 18 18](https://github.com/user-attachments/assets/93b2115e-3f01-46ec-a87a-e3f4c2a007eb)

**Comment by pyramation** [comment]
@karlhorky sure thing! I'd make sure if possible, to use 16.2.0 and pin exact versions — not sure if "latest" was used, but this can help in future

**Comment by karlhorky** [comment]
> I'd make sure if possible, to use 16.2.0 and pin exact versions

For our own projects, we do this.

It was coming up on fresh installs in new projects with students, where they ran `pnpm add libpg-query` (which I guess will also be a common use case for many other new projects too)

**Comment by punkpeye** [comment]
Feels heavily shortsighted implementation.

Why is `ignoredBuiltDependencies` exclude list and not an allow-list?
